### PR TITLE
Update mime types dependency

### PR DESCRIPTION
**Pull request by rymai**
We need to remove the `< 3` condition on the `mime-types` dependency to be able to upgrade `google-api-client` which depends on `mime-types ~> 3.0`.

See https://gitlab.com/gitlab-org/gitlab-ce/issues/38286#note_41303108 for more details.

/cc @godfat

### CODE REVIEW

**Comment by dosuken123** [comment]
This is critical for https://gitlab.com/gitlab-org/gitlab-ce/issues/35954. I hope we can merge this soon.

**Comment by dzaporozhets** [comment]
@dosuken123 how exactly its related?

**Review by dzaporozhets — APPROVED** [review]
Seems fine. I updated Gemfile.lock with the new rule. Once CI is green I will merge it

**Comment by dzaporozhets** [comment]
@rymai I pushed 2.8.2 to rubygems

**Comment by rymai** [comment]
@dzaporozhets Thanks!

**Pull request merged**
